name: color_ext
description: Extensions for Dart's native Color class.
version: 0.1.0
repository: https://github.com/Sparkles-Laurel/color_ext

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
